
       ▓██▓▄
    ▓▓▓▓██▓█▓▄
     ████████▓▒
          ▀▓▓███▄      ▄▄   ▄               ▌
         ▄▌▌▓▓████▄    ██ ▓█▀  ▄▌▀▄  ▓▓▌▄   ▓█  ▄▌▓▓▌▄ ▌▌   ▓
       ▓█████████▌▓▓   ██▓█▄  ▓█▄▓▓ ▐█▌  ██ ▓█  █▌  ██  █▌ █▓
      ▓▓▓▓▀▀▀▀▓▓▓▓▓▓▌  ██  █▓  ▓▌▄▄ ▐█▓▄▓█▀ █▓█ ▀█▄▄█▀   █▓█
       ▓▌                           ▐█▌                   █▌
        ▓
  
-dev

🐰 Keploy: 2023-09-26T05:51:09Z 	INFO	cmd/test.go:122		{"keploy test and mock path": "/files/keploy", "keploy testReport path": "/files/keploy/testReports"}
🐰 Keploy: 2023-09-26T05:51:12Z 	INFO	hooks/loader.go:748	keploy initialized and probes added to the kernel.
🐰 Keploy: 2023-09-26T05:51:12Z 	INFO	proxy/proxy.go:389	Keploy has hijacked the DNS resolution mechanism, your application may misbehave in keploy test mode if you have provided wrong domain name in your application code.
🐰 Keploy: 2023-09-26T05:51:12Z 	INFO	proxy/proxy.go:450	Proxy started at port:16789
🐰 Keploy: 2023-09-26T05:51:12Z 	INFO	proxy/proxy.go:640	starting DNS server at addr :16789
mockPath
/files/keploy/test-set-0
mocks
mockLen
9
🐰 Keploy: 2023-09-26T05:51:12Z 	INFO	hooks/launch.go:155	no error found while running user application container
$ bun run supabun.ts
🐰 Keploy: 2023-09-26T05:51:13Z 	INFO	hooks/launch.go:350	container & network found and processed successfully	{"time": 1695707473545789078}
🐰 Keploy: 2023-09-26T05:51:13Z 	INFO	hooks/launch.go:121	User application started successfully
🐰 Keploy: 2023-09-26T05:51:13Z 	INFO	test/test.go:187		{"no of test cases": 3, "test-set": "test-set-0"}
🐰 Keploy: 2023-09-26T05:51:23Z 	INFO	pkg/util.go:65	making a http request	{"test case id": "test-1"}
🐰 Keploy: 2023-09-26T05:51:23Z 	ERROR	pkg/util.go:89	failed sending testcase request to app	{"error": "Get \"http://172.20.0.3:420/hello\": dial tcp 172.20.0.3:420: connect: connection refused"}
🐰 Keploy: 2023-09-26T05:51:23Z 	INFO	test/test.go:223	result	{"testcase id": "test-1", "passed": "false"}
🐰 Keploy: 2023-09-26T05:51:23Z 	INFO	pkg/util.go:65	making a http request	{"test case id": "test-2"}
🐰 Keploy: 2023-09-26T05:51:23Z 	ERROR	pkg/util.go:89	failed sending testcase request to app	{"error": "Post \"http://172.20.0.3:420/save\": dial tcp 172.20.0.3:420: connect: connection refused"}
🐰 Keploy: 2023-09-26T05:51:23Z 	INFO	test/test.go:223	result	{"testcase id": "test-2", "passed": "false"}
🐰 Keploy: 2023-09-26T05:51:23Z 	INFO	pkg/util.go:65	making a http request	{"test case id": "test-3"}
🐰 Keploy: 2023-09-26T05:51:23Z 	ERROR	pkg/util.go:89	failed sending testcase request to app	{"error": "Get \"http://172.20.0.3:420/fetch\": dial tcp 172.20.0.3:420: connect: connection refused"}
🐰 Keploy: 2023-09-26T05:51:23Z 	INFO	test/test.go:223	result	{"testcase id": "test-3", "passed": "false"}
🐰 Keploy: 2023-09-26T05:51:23Z 	ERROR	test/test.go:309	failed to fetch test results	{"error": "🐰 Keploy:%!(EXTRA string=found no test results for test report with id: %v, string=report-3)"}
🐰 Keploy: 2023-09-26T05:51:23Z 	INFO	test/test.go:85	test run completed	{"passed overall": true}
🐰 Keploy: 2023-09-26T05:51:23Z 	INFO	hooks/loader.go:365	Exiting keploy program gracefully.
🐰 Keploy: 2023-09-26T05:51:23Z 	ERROR	hooks/ringBufReader.go:104	failed to receive signal from ringbuf socketDataEvent reader	{"error": "epoll wait: file already closed"}
Elysia is running at on port 420...
🐰 Keploy: 2023-09-26T05:51:24Z 	INFO	hooks/loader.go:414	eBPF resources released successfully...
🐰 Keploy: 2023-09-26T05:51:24Z 	ERROR	proxy/proxy.go:596	failed to accept connection to the proxy	{"error": "accept tcp [::]:16789: use of closed network connection"}
🐰 Keploy: 2023-09-26T05:51:24Z 	INFO	proxy/proxy.go:1079	Dns server stopped
🐰 Keploy: 2023-09-26T05:51:24Z 	INFO	proxy/proxy.go:1081	proxy stopped...
